/**
 * Created by Administrator on 2016/8/31.
 */
(function(z){
    var qT=function(){z.Q.call(this)};
    var rT=function(){var a=(0,window.$)(".QRCode-card"),b=(0,window.$)(".QRCode-toggleButton"),c=(0,window.$)(".QRCode-toggleButtonText",b);(0,window.$)("body").on("click",function(d){a.is(":visible")?Boolean((0,window.$)(d.target).closest(a).length)||(a.addClass("fadeOutDown").onTransitionEnd(function(){a.hide().removeClass("fadeOutDown")},200),c.text("下载知乎 App")):Boolean((0,window.$)(d.target).closest(b).length)&&(a.addClass("fadeInUp").show().onTransitionEnd(function(){a.removeClass("fadeInUp")},200),
        c.text("关闭二维码"))})};var sT=function(){var a=(0,window.$)(".sign-flow");if(a.length){var b=new tT;b.w(a[0]);b.g("trackRequested",function(a){a.preventDefault();a.label="home_default";z.zi(a)})}};
    var uT=function(){function a(){var a=window.particlesJS;a&&((0,window.$)("\x3cdiv\x3e",{id:"particles"}).appendTo("body"),a("particles",c))}var b=!!window.HTMLCanvasElement,c={particles:{number:{value:20,density:{enable:!0,value_area:1E3}},color:{value:"#e1e1e1"},shape:{type:"circle",stroke:{width:0,color:"#000000"},polygon:{nb_sides:5},image:{src:"img/github.svg",width:100,height:100}},opacity:{value:.5,random:!1,anim:{enable:!1,speed:1,opacity_min:.1,sync:!1}},size:{value:15,random:!0,anim:{enable:!1,
        speed:180,size_min:.1,sync:!1}},line_linked:{enable:!0,distance:650,color:"#cfcfcf",opacity:.26,width:1},move:{enable:!0,speed:2,direction:"none",random:!0,straight:!1,out_mode:"out",bounce:!1,attract:{enable:!1,rotateX:600,rotateY:1200}}},interactivity:{detect_on:"canvas",events:{onhover:{enable:!1,mode:"repulse"},onclick:{enable:!1,mode:"push"},resize:!0},modes:{grab:{distance:400,line_linked:{opacity:1}},bubble:{distance:400,size:40,duration:2,opacity:8,speed:3},repulse:{distance:200,duration:.4},
        push:{particles_nb:4},remove:{particles_nb:2}}},retina_detect:!0};(0,window.$)(function(){b&&window.$.ajax({url:"/static/revved/components/particles.js/particles.min.00debcf6.js",dataType:"script",cache:!0}).then(a)})};var tT=function(){z.Q.call(this)};var vT=function(a){return!/^\+?[0-9]+$/.test(a)};var wT=function(a,b){a.account&&(a[b]=a.account,delete a.account)};
    var xT=function(a){var b=(0,window.$)(".index-tab-navs a",a.m()),c=(0,z.t)(function(){var a=window.location.hash||b.filter(".active").attr("href"),c=b.filter(function(){return(0,window.$)(this).attr("href")===a});c.addClass("active").siblings().removeClass("active");c.parent().attr("data-active-index",c.index());"#signin"===a?this.dl.is(":visible")||(this.gf.hide(),this.dl.show(),this.Ol()):"#signup"!==a||this.gf.is(":visible")||(this.dl.hide(),this.gf.show(),this.Ol())},a);a.o().g(window,"hashchange",
        c);c()};var yT=function(a){a.dl=(0,window.$)(".view-signin",a.m());var b=(0,window.$)("form",a.dl),c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},z.Wm,{submitHandler:z.sk(c,window.$.proxy(a.OA,a))}));var d=(0,window.$)('input[name\x3d"account"]',b);(0,window.$)(".unable-login",a.dl).click(function(){(new z.Dk(d.val())).show()});b=(0,window.$)(".captcha-module, .Captcha",b).get(0);a.$t=new z.bk("login");a.$t.w(b);z.fk(a.$t)};
    var zT=function(a){a.gf=(0,window.$)(".view-signup",a.m());var b=(0,window.$)("form",a.gf);a.Rh=!(0,window.$)('input[name\x3d"phone_num"]',b).length;var c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},z.Wm,{submitHandler:z.sk(c,window.$.proxy(a.Op,a))}));var d=(0,window.$)('input[name\x3d"account"]',b);a.gf.on("click",".switch-to-login",function(){window.location.hash="#signin";var b=d.val();b&&(0,window.$)('input[name\x3d"account"]',a.JY).val(b)}).on("change",".agreement input",function(){var a=
        (0,window.$)(this);a.is(":checked")&&a.parents(".agreement").find(".error").remove()});c=(0,window.$)(".input-wrapper[data-type]",b).get(0);a.Yp=new z.bk;a.Yp.w(c);z.fk(a.Yp);a.hn=new z.Qk(b);a.hn.start()};var AT=function(){var a=z.$i.get("accountcallback");z.$i.remove("accountcallback");if(a){a=(0,window.decodeURIComponent)(a);try{var b=JSON.parse(a);z.W.dispatchEvent(new z.Xj("accountcallback",b))}catch(c){}}};z.y(qT,z.Q);qT.prototype.init=function(){this.w(window.document.body)};
    qT.prototype.C=function(a){qT.v.C.call(this,a);sT();uT();rT();z.zi({category:"view_home",action:"visit_home"})};z.y(tT,z.Q);z.e=tT.prototype;z.e.C=function(){tT.v.C.call(this);this.Gz()};z.e.ma=function(a){this.dispatchEvent(window.$.extend({type:"trackRequested"},a))};
    z.e.Gz=function(){function a(a,b){(0,window.$)(":submit",a).click(function(){return b(a)});(0,window.$)("keydown",a).click(function(c){if(13===c.keyCode)return b(a)})}yT(this);zT(this);this.Qo();AT();this.Ol();xT(this);var b=this,c=this.m();a((0,window.$)(".view-signin form",c),function(a){a=a.ye().account;var c=vT(a);b.ma({category:"sign_in",action:a?"click_sign_in_submit_"+(c?"email":"phone"):"click_sign_in_submit_no_channel"})});a((0,window.$)(".view-signup form",c),function(a){a=a.ye();a=a.phone_num||
        a.account;var c=b.Rh?vT(a):!1;b.ma({category:"sign_up",action:a?b.Rh?"click_sign_up_submit_"+(c?"email":"phone"):"click_sign_up_submit_phone":"click_sign_up_submit_no_channel"})});(0,window.$)(".js-bindweibo",c).click(function(){b.ma({category:"sign_in_or_sign_up",action:"click_sign_with_weibo_start"});z.Yj("sina")});(0,window.$)(".js-bindqq",c).click(function(){b.ma({category:"sign_in_or_sign_up",action:"click_sign_with_qq_start"});z.Yj("qq")});(0,window.$)(".js-bindwechat",c).click(function(){b.ma({category:"sign_in_or_sign_up",
        action:"click_sign_with_wechat_start"});z.Yj("wechat")});(0,window.$)(".js-toggle-sns-buttons").click(function(){var a=(0,window.$)(".sns-buttons");a.hasClass("is-visible")?a.onTransitionEnd(function(){a.css("visibility","hidden")},250).removeClass("is-visible"):a.css("visibility","visible").addClass("is-visible")})};
    z.e.OA=function(a){var b=this,c=(0,window.$)(a),d=c.ye(),f=vT(d.account);this.ma({category:"sign_in",action:"sign_in_front_end_pass_"+(f?"email":"phone")});a=f?"/login/email":"/login/phone_num";z.Fk&&(d.is_org_page=1);f?wT(d,"email"):wT(d,"phone_num");var g=this.$t.info();return window.$.post(a,d,function(a){var k=a&&!a.r,l=Object.assign({},{status:{result:k?"Success":a.data&&a.data.captcha?"BadCaptcha":"Fail"}},g);k?(b.ma({Gc:!0,category:"sign_in",action:"sign_in_success_"+(f?"email":"phone")}),
        b.$d()):(k=a.errcode,1991831===k?(a=new z.Bk({data:{phone_num:d.phone_num,password:d.password},HU:function(a){c.data("validator").showErrors(a)}}),a.Gb(b),a.G(!0)):200001===k?(a='机构帐号\x3cspan\x3e · \x3c/span\x3e\x3ca href\x3d"/org/signin"\x3e点此登录\x3c/a\x3e',z.Fk&&(a='个人帐号\x3cspan\x3e · \x3c/span\x3e\x3ca href\x3d"/signin"\x3e点此登录\x3c/a\x3e'),c.data("validator").showErrors({account:a})):(z.fk(b.$t),c.data("validator").showErrors(a.data)));b.trackEvent(b.dl.get(0),"SignIn","Button",l)})};
    z.e.Op=function(a){var b=this;a=(0,window.$)(a);var c=a.ye(),d=b.Rh?vT(c.account):!1;b.ma({Gc:!0,category:"sign_up",action:"sign_up_front_end_pass_"+(d?"email":"phone")});var f=d?"/register/email":"/register/phone_num/validation";z.Fk&&(d=!0,f="/register/org");d?wT(c,"email"):wT(c,"phone_num");var g=this.hn.stop();c.userInfo=JSON.stringify(g);var h=a.data("validator"),k=b.Yp.info();return window.$.post(f,c,function(a){var f=a&&!a.r,g=Object.assign({},{status:{result:f?"Success":a.data&&a.data.captcha?
        "BadCaptcha":"Fail"}},k);d?f?(b.ma({Gc:!0,category:"sign_up",action:"sign_up_success_email"}),b.$d()):(z.fk(b.Yp),h.showErrors(a.data)):f?(a=new z.vw(c),a.Gb(b),a.G(!0)):(z.fk(b.Yp),b.Rh||wT(a.data,"phone_num"),h.showErrors(a.data));b.trackEvent(b.gf.get(0),"SignUp","Button",g)})};z.e.Ol=function(){if(!z.vk){var a=this.m();(0,window.setTimeout)(function(){(0,window.$)("input[placeholder]:visible",a).placeholder()},10)}};z.e.Qo=function(){z.ak(this.o(),this.VT)};
    z.e.VT=function(a){a=a.Nf;var b={qqconn:"qq",wechat:"wechat",sina:"weibo"}[a.type];1===a.login?(this.ma({Gc:!0,category:"sign_in",action:"sign_in_success_"+b}),this.$d()):(a=new z.Ik(a),a.Gb(this),a.show())};z.e.$d=function(){var a=(new z.rh(window.location.href)).zd().get("next");a?window.location.href=a:window.location.reload()};z.e.trackEvent=function(a,b,c,d){z.Y.trackEvent(a,{action:b,element:c},d)};z.x("ZH.entrySignPage",function(){(new qT).init()});z.lg("page-index");}).call(this, __z_z__);